crypto_coins = {
    "stable_coins": ["BUSD","BGBP","PAX","TUSD","USDT", "USDC"],
    "popular_coins": ["BTC", "ETH", "BNB"]
}
crypto_tokens = {
    "Storage coins": ["AR","BLZ","BTTC","FIL", "HOT","PROM","RIF","SC","SNM","STORJ","STX"],
    "Meme": ["DOGE", "FLOKI", "PEPE","PEOPLE","SHIB"],
    "AI": ["AGIX","CTXC", "FET","MDT","NMR","OCEAN""PHB","WLD"],
    "Metaverse": ["ALICE","AXS","BURGER","COMBO","DAR","FLOKI","GHST","HIGH","ILV","MAGIC","MANA","MBOX","PYR","SAND","SLP","TLM","TVK"],
    "Infrastructure": ["ADX","ANT","API3","ARKM","ARPA","ASTR","ATA","BAT","BICO","CLV","CTK","CVC","DATA","DENT","LINK", "BAND"],
    "Fan Token": ["ACM","ALPINE","ASR","ATM","BAR","CHZ","CITY","JUV","LAZIO","OG","PORTO","PSG","SANTOS"],
    "Launchpad": ["ALPHA","ALPINE","ARKM","AXS","BAND","BETA","BNB","BTTC","C98","CELR","CTSI","DEGO","EDU","EGLD","FET","GFT","GMT","HOOK","ID","INJ","KAVA","LAZIO","LOKA","MATIC","ONE","PERL","PORTO","SAND","SFP","TKO","TROY","VOXEL","WRX"],
    "Launchpool": ["ALICE","ALPHA", "ASR","ATA","ATM","BEL","CITY","CTK","DAR","DODO","FLM","GAL","HARD","HFT","HIGH","JUV","KLAY","LIT","MAV","MBOX","MC","OG","PENDLE","PSG","QI","RDNT","SANTOS","SUI","TLM","UNFI","WING","XVS"],
    "POW": ["ANKR","BCH","BTC","CFX", "CKB","CTXC","DASH","DCR","DGB","DOGE","ETC","FLUX","IOTA","KDA","KMD","LTC","NKN","ONT","QKC","RIF","RVN","SC","TRB","WTC","XMR","XVG","ZEC","ZEN","ZIL"],
    "Layer 1/ Layer 2": ["ACA","ADA","ALGO","AMB","APT","ARB","ARDR","ARK","ARPA","ASTR","ATOM","AVAX","BNB","BTS","CELO","CELR","CFX","CHR","CKB","CTSI","CTXC","DCR","DOT","DREP","EGLD","ELF","EOS","ETC","ETH","FLOW","FLUX","FTM","GLMR","GNO","HBAR","HIVE","HOT","ICP","ICX","INJ","IOST","IOTA","IOTX","KAVA","KDA","KLAY","KSM","LOOM","LSK","LUNA","LUNC","MATIC","MINA","MOVR","NEAR","NULS","OMG","ONE","ONT","OP","OSMO","PHB","PROM","QKC","QTUM","REEF","REI","RIF","SCRT","SKL","SOL","STRAX","STX","SUI","SYS","TOMO","TRX","VET","VIDT","VITE","WAN","WAXP","XEM","XLM","XRP","XTZ","ZIL"],
    "NFT": ["AGLD","ALICE","APE","AUDIO","AXS","BNX","CHR","CHZ","COMBO","DAR","ENJ","ERN","FIO","GALA","GHST","GMT","HIGH","IMX","MAGIC","MANA","MBOX","OGN","PYR","RARE","SAND","SLP","SUPER","THETA","TVK","WAXP"],
    "Gaming": ["AGLD","ALICE","AXS","BNX","BURGER","COMBO","DAR","ENJ","FLOKI","GALA","GHST","ILV","IMX","LOKA","MAGIC","MANA","MBOX","MC","PLA","PYR","SAND","SLP","TLM","VOXEL","WAXP","YGG"],
    "Innovation": ["AGLD","ALICE","ALPHA","AMB","ARK","ARKM","ATA","ATM","AUCTION","BADGER","BAKE","BAR","BEL","BIFI","BNX","BSW","BTS","BURGER","CHESS","CREAM","CVP","CVX","DEGO","DEXE","DF","DODO","DREP","EPX","ERN","FIS","FLM","FLOKI","FOR","FRONT","FTT","GAL","GHST","GMX","GNS","HFT","HOOK","ID","JASMY","JUV","KP3R","LEVER","LINA","LIT","LQTY","MAGIC","MDX","MLN","OAX","OG","OM","OMG","OOKI","PENDLE","PEOPLE","PEPE","PERL","PERP","PHA","PNT","POLS","POND","PROM","PSG","RDNT","REEF","RPL","SLP","SNM","SRM","STG","SUN","SUPER","SUSHI","SYN","TORN","TRN","UFT","UNFI","VGX","VIDT","WING","WNXM","WRX","YFII"],
    "DeFi": ["1INCH","AAVE","ACA","AKRO","ALCX","ALPACA","AMP","ANKR","AST","AUCTION","AST","BADGER","BAKE","BAL","BAND","BEL","BETA","BIFI","BNT","BOND","BSW","BTS","C98","CAKE","CELO","CHESS","COMP","COTI","CREAM","CRV","CVP","CVX","DEGO","DEXE","DF","DIA","DODO","DYDX","EPX","FARM","FIDA","FIS","FLM","FOR","FORTH","FRONT","FXS","GHST","GMX","GNS","HARD","HFT","HIFI","IDEX","INJ","JOE","JST","KAVA","KLAY","KNC","KP3R","LDO","LEVER","LINA","LIT","LQTY","LRC","LUNA","LUNC","MAV","MBOX","MDX","MKR","MLN","MULTI","NMR","OM","OOKI","OSMO","PENDLE","PERP","PNT","POLS","POND","PROS","QI","QUICK","RAY","RDNT","REEF","REN","RIF","RPL","RSR","RUNE","SNX","SPELL","SRM","STG","SUN","SUPER","SUSHI","SYN","TRB","TRU","UFT","UMA","UNFI","UNI","USTC","WAXP","WING","WOO","XVS","YFI","YFII","ZRX"],
    "ETF": ["ADADOWN","ADADOWN","BNBDOWN","BNBUP","BTCDOWN","BTCUP","ETHDOWN","ETHUP"],
    "Polkadot": ["ACA","AKRO","ASTR","ATA","DOT","GLMR","KSM","LIT","PHA","REEF"],
}
