crypto_coins = {
    "stable_coins": ["FDUSD","TUSD","USDT", "USDC"],
    "popular_coins": ["BTC", "ETH", "BNB"]
}
crypto_tokens = {
    "AI": ["-","AGIX","AI","CTXC", "FET","GRT","IQ","MDT","NFP","NMR","OCEAN","PHB","RLC","THETA","WLD"],
    "DeFi": ["1INCH","AAVE","ACA","AEVO","AKRO","ALCX","ALPACA","ALPHA","AMP","ANKR","AST","AUCTION","BADGER","BAKE","BAL","BAND","BEL","BETA","BIFI","BNT","BOND","BSW","BTS","C98","CAKE","CELO","CHESS","COMP","CREAM","CRV","CVP","CVX","DEGO","DEXE","DF","DIA","DODO","DYDX","EPX","ETHFI","FARM","FIDA","FIS","FLM","FOR","FORTH","FRONT","FXS","GHST","GMX","GNS","HARD","HFT","HIFI","IDEX","INJ","JOE","JST","JUP","KAVA","KLAY","KNC","KP3R","LDO","LEVER","LINA","LIT","LQTY","LRC","LUNA","LUNC","MAV","MBOX","MDX","MKR","MLN","NMR","OOKI","OSMO","PENDLE","PERP","PNT","POLS","POND","PROS","QI","QUICK","RAY","RDNT","REEF","REN","RIF","RPL","RSR","RUNE","SNX","SPELL","STG","SUN","SUPER","SUSHI","SYN","TRB","TRU","UFT","UMA","UNFI","UNI","USTC","WAXP","WING","WNXM","WOO","XVS","YFI","ZRX"],
    "Fan Token": ["ACM","ALPINE","ASR","ATM","BAR","CHZ","CITY","JUV","LAZIO","OG","PORTO","PSG","SANTOS"],
    "Gaming": ["AGLD","ALICE","AXS","BNX","BURGER","COMBO","DAR","ENJ","FLOKI","GALA","GHST","ILV","IMX","LOKA","MAGIC","MANA","MBOX","MC","PLA","PYR","SAND","SLP","TLM","VOXEL","WAXP","YGG"],
    "Infrastructure": ["ADX","ALT","ANT","API3","ARKM","ARPA","ASTR","ATA","AXL","BAND","BAT","BICO","CLV","CTK","CVC","CYBER","DATA","DENT","DIA","DOCK","DUSK","DYM","FET","FIO","GAL","GLM","GRT","GTC","HOOK","ID","IOTX","JASMY","KEY","LINK","LPT","MASK","MDT","MTL","OCEAN","OXT","PHA","POLYX","PYTH","QNT","RAD","RLC"],
    "Meme": ["1000SATS","BOME","BONK","DOGE", "FLOKI","MEME","ORDI","PEOPLE","PEPE","SHIB","WIF"],
    "Metaverse": ["ALICE","AXS","BURGER","COMBO","DAR","FLOKI","GHST","HIGH","ILV","MAGIC","MANA","MBOX","PYR","SAND","SLP","TLM","TVK","VANRY"],
    "Launchpad": ["ALPHA","ALPINE","ARKM","AXS","BAND","BETA","BNB","BTTC","C98","CELR","CTSI","DEGO","EDU","EGLD","FET","GFT","GMT","HOOK","ID","INJ","KAVA","LAZIO","LOKA","MATIC","ONE","PERL","PORTO","SAND","SFP","TKO","TROY","VOXEL","WRX"],
    "Launchpool": ["ALICE","ALPHA", "ASR","ATA","ATM","BEL","CITY","CTK","DAR","DODO","FLM","GAL","HARD","HFT","HIGH","JUV","KLAY","LIT","MAV","MBOX","MC","OG","PENDLE","PSG","QI","RDNT","SANTOS","SUI","TLM","UNFI","WING","XVS"],
    "Layer 1/ Layer 2": ["ACA","ADA","ALGO","AMB","APT","ARB","ARDR","ARK","ARPA","ASTR","ATOM","AVAX","BNB","BTS","CELO","CELR","CFX","CHR","CHZ","CKB","CTSI","CTXC","DCR","DOT","DREP","DYM","EGLD","ELF","EOS","ETC","ETH","FLOW","FLUX","FTM","GLMR","GNO","HBAR","HIVE","HOT","ICP","ICX","IMX","INJ","IOST","IOTA","IOTX","KAVA","KDA","KLAY","KSM","LOOM","LSK","LTO","LUNA","LUNC","MANTA","MATIC","METIS","MINA","MOVR","NEAR","NEO","NTRN","NULS","OM","OMG","ONE","ONT","OP","OSMO","PHB","PROM","QKC","QTUM","REEF","REI","RIF","RONIN","ROSE","SCRT","SEI","SKL","SOL","STRK","STX","SUI","SYS","SYS","THETA","TRX","VANRY","VET","VIDT","VITE","WAN","WAXP","XEM","XLM","XRP","XTZ","ZIL"],
    "Liquid Staking":["ANKR","CHESS","FIS","FXS","JTO","LDO","QI","RPL","WBETH"],
    "NFT": ["AGLD","ALICE","APE","AUDIO","AXS","BNX","CHR","CHZ","COMBO","DAR","ENJ","ERN","FIO","GALA","GHST","GMT","HIGH","IMX","MAGIC","MANA","MBOX","OGN","PYR","RARE","SAND","SLP","SUPER","THETA","TVK","WAXP"],
    "Payments":["ACH","BCH","BTC","COTI","LTC","PUNDIX","UTK","XNO","XRP"],
    "Polkadot": ["ACA","AKRO","ASTR","ATA","DOT","GLMR","KSM","LIT","PHA","REEF"],
    "POW": ["ANKR","BCH","BTC","CFX", "CKB","CTXC","DASH","DCR","DGB","DOGE","ETC","FLUX","IOTA","KDA","KMD","LTC","NKN","ONT","QKC","RIF","RVN","SC","TRB","WTC","XMR","XVG","ZEC","ZEN","ZIL"],
    "RWA":["AVAX","CHR","DUSK","ICP","LTO","MKR","OM","PENDLE","RSR","SNX","TRU"],
    "Seed": ["100SATS","ACE","AEVO","AGLD","AI","ALICE","ALPHA","ALT","ARKM","ASR","ATA","ATM","AUCTION","AXL","BADGER","BAKE","BAR","BEL","BIFI","BLUR","BNX","BOME","BONK","BSW","BURGER","CHESS","CVP","CVX","DEGO","DEXE","DF","DODO","DYM","EPX","ERN","ETHFI","FIS","FLM","FLOKI","FOR","FRONT","GAL","GHST","GMX","GNS","HFT","HOOK","ID","JTO","JUP","JUV","LEVER","LIT","LIT","LQTY","MAGIC","MANTA","MDX","MEME","METIS","NFP","OG","OG","OM","ORDI","PENDLE","PEOPLE","PEPE","PERP","PHA","PIXEL","PNT","POLS","POND","PORTAL","PROM","PROS","PSG","PYTH","RDNT","RONIN","RPL","SLP","STG","STRK","SUN","SUPER","SYN","TIA","TRU","UFT","UNFI","VANRY","VIDT","VIDT","WING","WNXM","WRX","XAI"],
    "Storage coins": ["AR","BLZ","BTTC","FIL", "HOT","RIF","SC","STORJ","STX"],
}
crypto_dict = {
    '1INCH': '1inch',
    '1000SATS': '1000 SATS Ordinals',
    'AAVE': 'Aave',
    'ACA': 'Acala',
    'ACE': 'Fusionist',
    'ACH': 'Alchemy Pay',
    'ACM': 'AC Milan Fan Token',
    'ADA': 'Cardano',
    'ADADOWN': 'ADA Down',
    'ADX': 'AdEx',
    'AEVO': 'Aevo',
    'AGIX': 'SingularityNET',
    'AGLD': 'Adventure Gold',
    'AI': 'Sleepless AI',
    'AKRO': 'Akropolis',
    'ALCX': 'Alchemix',
    'ALGO': 'Algorand',
    'ALICE': 'MyNeighborAlice',
    'ALPACA': 'Alpaca Finance',
    'ALPHA': 'Stella',
    'ALPINE': 'Alpine F1 Team Fan Token',
    'ALT': 'AltLayer',
    'AMB': 'AirDAO',
    'AMP': 'Amp',
    'ANKR': 'Ankr',
    'ANT': 'Aragon',
    'APE': 'ApeCoin',
    'API3': 'API3',
    'APT': 'Aptos',
    'AR': 'Arweave',
    'ARB': 'Arbitrum',
    'ARDR': 'Ardor',
    'ARK': 'Ark',
    'ARKM': 'Arkham',
    'ARPA': 'ARPA Network',
    'ASR': 'AS Roma Fan Token',
    'AST': 'AirSwap',
    'ASTR': 'Astar',
    'ATA': 'Automata Network',
    'ATM': 'Atletico Madrid Fan Token',
    'ATOM': 'Cosmos',
    'AUCTION': 'Auction',
    'AUDIO': 'Audius',
    'AVAX': 'Avalanche',
    'AXS': 'Axie Infinity',
    'AXL': 'Axelar',
    'BADGER': 'Badger DAO',
    'BAKE': 'BakeryToken',
    'BAL': 'Balancer',
    'BAND': 'Band Protocol',
    'BAR': 'Barcelona FC Fan Token',
    'BAT': 'Basic Attention Token',
    'BCH': 'Bitcoin Cash',
    'BEL': 'Bella Protocol',
    'BETA': 'Beta Finance',
    'BICO': 'Biconomy',
    'BIFI': 'Beefy.Finance',
    'BLUR': 'Blur',
    'BLZ': 'Bluzelle',
    'BNB': 'Binance Coin',
    'BNBDOWN': 'BNB Down',
    'BNBUP': 'BNB Up',
    'BNT': 'Bancor',
    'BNX': 'BinaryX',
    'BOME': 'Book of MEME',
    'BOND': 'BarnBridge',
    'BONK': 'Bonk',
    'BSW': 'Biswap',
    'BTC': 'Bitcoin',
    'BTCDOWN': 'BTC Down',
    'BTCUP': 'BTC Up',
    'BTS': 'BitShares',
    'BTTC': 'Bitcoin Token',
    'BURGER': 'BurgerCities',
    'C98': 'Coin98',
    'CAKE': 'PancakeSwap',
    'CELO': 'Celo',
    'CELR': 'Celer Network',
    'CFX': 'Conflux Network',
    'CHESS': 'Tranchess',
    'CHR': 'Chromia',
    'CHZ': 'Chiliz',
    'CITY': 'Manchester City Fan Token',
    'CKB': 'CKB',
    'CLV': 'Clover Finance',
    'COMBO': 'COMBO',
    'COMP': 'Compound',
    'COTI': 'COTI',
    'CREAM': 'Cream Finance',
    'CRV': 'Curve DAO Token',
    'CTK': 'CertiK',
    'CTSI': 'Cartesi',
    'CTXC': 'Cortex',
    'CVC': 'Civic',
    'CVP': 'PowerPool',
    'CVX': 'Convex Finance',
    'CYBER': 'CyberConnect',
    'DAR': 'Mines of Dalarnia ',
    'DASH': 'Dash',
    'DATA': 'Streamr DATAcoin',
    'DCR': 'Decred',
    'DEGO': 'DEGO Finance',
    'DENT': 'Dent',
    'DEXE': 'DeXe',
    'DF': 'dForce',
    'DGB': 'DigiByte',
    'DIA': 'DIA',
    'DOCK': 'Dock',
    'DODO': 'DODO',
    'DOGE': 'Dogecoin',
    'DOT': 'Polkadot',
    'DREP': 'DREP',
    'DUSK': 'Dusk',
    'DYDX': 'dYdX',
    'DYM': 'Dymension',
    'EDU': 'EduCoin',
    'EGLD': 'MultiversX',
    'ELF': 'aelf',
    'ENJ': 'Enjin Coin',
    'ENS': 'Ethereum Name Service',
    'EOS': 'EOS',
    'EPX': 'Ellipsis',
    'ERN': 'Ethernity Chain',
    'ETC': 'Ethereum Classic',
    'ETH': 'Ethereum',
    'ETHDOWN': 'ETH Down',
    'ETHFI': 'Ether.fi',
    'ETHUP': 'ETH Up',
    'FARM': 'Harvest Finance',
    'FET': 'Fetch.ai',
    'FIDA': 'Bonfida',
    'FIL': 'Filecoin',
    'FIO': 'FIO Protocol',
    'FIS': 'StaFi',
    'FLM': 'Flamingo Finance',
    'FLOKI': 'Floki Inu',
    'FLOW': 'Flow',
    'FLUX': 'Flux',
    'FOR': 'ForTube',
    'FORTH': 'Ampleforth Governance Token',
    'FRONT': 'Frontier',
    'FTM': 'Fantom',
    'FTT': 'FTX Token',
    'FXS': 'Frax Share',
    'GAL': 'Galxe',
    'GALA': 'Gala games',
    'GFT': 'Gifted Hands Token',
    'GHST': 'Aavegotchi',
    'GLM': 'Golem',
    'GLMR': 'Glimmer',
    'GMT': 'GoMining Token',
    'GMX': 'GMX',
    'GNO': 'Gnosis',
    'GRT': 'The Graph',
    'GTC': 'Gitcoin',
    'GNS': 'Gains Network',
    'HARD': 'Kava Lend',
    'HBAR': 'Hedera Hashgraph',
    'HFT': 'Hashflow',
    'HIFI': 'Hifi Finance',
    'HIGH': 'Highstreet',
    'HIVE': 'Hive',
    'HOOK': 'HooKed Protocol',
    'HOT': 'Holo',
    'ICP': 'Internet Computer',
    'ICX': 'ICON',
    'ID': 'Space ID',
    'IDEX': 'IDEX',
    'ILV': 'Illuvium',
    'IMX': 'ImmutableX',
    'INJ': 'Injective Protocol',
    'IOST': 'IOST',
    'IOTA': 'IOTA',
    'IOTX': 'IoTeX',
    'IQ': 'IQ',
    'JASMY': 'JasmyCoin',
    'JOE': 'JOE',
    'JST': 'JUST',
    'JTO': 'JITO',
    'JUV': 'Juventus Fan Token',
    'JUP': 'Jupiter',
    'KAVA': 'Kava',
    'KDA': 'Kadena',
    'KEY': 'Selfkey',
    'KLAY': 'Klaytn',
    'KMD': 'Komodo',
    'KNC': 'Kyber Network',
    'KP3R': 'Keep3rV1',
    'KSM': 'Kusama',
    'LAZIO': 'Lazio Fan Token',
    'LDO': 'Lido DAO Token',
    'LEVER': 'LeverFi',
    'LINA': 'Linear',
    'LINK': 'Chainlink',
    'LIT': 'Litentry',
    'LOKA': 'Lokanet',
    'LOOM': 'Loom Network',
    'LPT': 'Livepeer',
    'LQTY': 'Liquity',
    'LRC': 'Loopring',
    'LSK': 'Lisk',
    'LTC': 'Litecoin',
    'LTO': 'LTO Network',
    'LUNA': 'Terra',
    'LUNC': 'Terra Classic',
    'MAGIC': 'Treasure Magic',
    'MANA': 'Decentraland',
    'MANTA': 'Manta',
    'MASK': 'Mask Network',
    'MATIC': 'Polygon',
    'MAV': 'Mavro',
    'MBOX': 'Mobox',
    'MC': 'Mercury',
    'MDT': 'Measurable Data Token',
    'MDX': 'Mdex',
    'MEME': 'Memecoin',
    'METIS': 'MetisDAO',
    'MINA': 'Mina Protocol',
    'MKR': 'Maker',
    'MLN': 'Enzyme',
    'MTL': 'Metal',
    'MOVR': 'Moonriver',
    'MULTI': 'MultiVAC',
    'NEAR': 'NEAR Protocol',
    'NEO': 'NEO',
    'NFP': 'NFPrompt Token',
    'NKN': 'NKN',
    'NMR': 'Numeraire',
    'NTRN': 'Neutron',
    'NULS': 'NULS',
    'OAX': 'OAX',
    'OCEAN': 'Ocean Protocol',
    'OG': 'OG Fan Token',
    'OGN': 'Origin Protocol',
    'OM': 'MANTRA DAO',
    'OMG': 'OMG Network',
    'ONE': 'Harmony',
    'ONT': 'Ontology',
    'OOKI': 'Ooki Protocol',
    'OP': 'Optimism',
    'ORDI': 'Ordi',
    'ORN': 'Orion Protocol',
    'OSMO': 'Osmosis',
    'OXT': 'Orchid',
    'PENDLE': 'Pendle',
    'PEOPLE': 'Constitutional DAO',
    'PEPE': 'Pepe',
    'PERL': 'Perlin',
    'PERP': 'Perpetual Protocol',
    'PHA': 'Phala Network',
    'PHB': 'Phoenix',
    'PIXEL': 'Pixels',
    'PLA': 'PlayDapp',
    'PNT': 'pNetwork',
    'POLS': 'Polkastarter',
    'POLYX': 'Polymesh',
    'POND': 'Marlin',
    'PORTAL': 'Portal',
    'PORTO': 'Porto',
    'PROM': 'Prometeus',
    'PROS': 'Prosper',
    'PSG': 'Paris Saint-Germain Fan Token',
    'PUNDIX': 'Pundi X',
    'PYR': 'Pyrrha',
    'PYTH': 'Pyth Network',
    'QI': 'BENQI',
    'QNT': 'Quant',
    'QKC': 'QuarkChain',
    'QTUM': 'Qtum',
    'QUICK': 'QuickSwap',
    'RAD': 'Radworks',
    'RARE': 'SuperRare',
    'RAY': 'Raydium',
    'RDNT': 'Radiant Capital',
    'REEF': 'Reef Finance',
    'REI': 'REI Network',
    'REN': 'Ren',
    'RIF': 'Rootstock Infrastructure Framework',
    'RLC': 'iExecRLC',
    'RONIN': 'Ronin',
    'ROSE': 'Oasis Network',
    'RPL': 'Rocket Pool',
    'RSR': 'Reserve Rights',
    'RUNE': 'THORChain',
    'RVN': 'Ravencoin',
    'SAND': 'The Sandbox',
    'SANTOS': 'Santos FC Fan Token',
    'SC': 'Siacoin',
    'SCRT': 'Secret',
    'SEI': 'Sei',
    'SFP': 'SafePal',
    'SHIB': 'Shiba Inu',
    'SKL': 'Skale Network',
    'SLP': 'Smooth Love Potion',
    'SNM': 'SONM',
    'SNX': 'Synthetix Network',
    'SOL': 'Solana',
    'SPELL': 'Spell Token',
    'SRM': 'Serum',
    'STG': 'Stargate Finance',
    'STORJ': 'Storj',
    'STRAX': 'Stratis',
    'STRK': 'Starknet Token',
    'STX': 'Stacks',
    'SUI': 'Sui',
    'SUN': 'Sun Token',
    'SUPER': 'SuperVerse',
    'SUSHI': 'SushiSwap',
    'SXP': 'Solar',
    'SYN': 'Synapse',
    'SYS': 'Syscoin',
    'THETA': 'Theta Network',
    'TIA': 'Celestia',
    'TKO': 'Tokocrypto',
    'TLM': 'Alien Worlds',
    'TOMO': 'TomoChain',
    'TORN': 'Tornado Cash',
    'TRB': 'Tellor Tributes',
    'TRN': 'Trodl',
    'TROY': 'Troy',
    'TRU': 'TrueFi',
    'TRX': 'TRON',
    'TVK': 'Terra Virtua Kolect',
    'UFT': 'UniLend Finance',
    'UMA': 'UMA',
    'UNFI': 'Unifi Protocol DAO',
    'UNI': 'Uniswap',
    'USTC': 'TerraClassicUSD',
    'UTK': 'xMoney',
    'VANRY': 'Vanar',
    'VET': 'VeChain',
    'VGX': 'Voyager Token',
    'VIC': 'Viction',
    'VIDT': 'VIDT DAO',
    'VITE': 'VITE',
    'VOXEL': 'Voxel',
    'WAN': 'Wanchain',
    'WAVES': 'Waves',
    'WAXP': 'WAX',
    'WBETH': 'Wrapped Beacon ETH',
    'WIF': 'Dogwifhat',
    'WING': 'Wing Token',
    'WLD': 'World coin Token',
    'WNXM': 'Wrapped NXM',
    'WOO': 'WOO Network',
    'WRX': 'WazirX',
    'WTC': 'Waltonchain',
    'XAI':'Xai',
    'XEM': 'NEM',
    'XLM': 'Stellar Lumens',
    'XMR': 'Monero',
    'XNO': 'Nano',
    'XRP': 'Ripple',
    'XTZ': 'Tezos',
    'XVG': 'Verge',
    'XVS': 'Venus',
    'YFI': 'yearn.finance',
    'YGG': 'Yield Guild Games',
    'ZEC': 'Zcash',
    'ZEN': 'Horizen',
    'ZIL': 'Zilliqa',
    'ZRX': '0x'
}
fiat_dict = {
    'BGBP': 'Binance GBP',
    'BUSD': 'Binance USD',
    'BTC': 'Bitcoin',
    'BNB': 'Binance Coin',
    'PAX': 'Paxos Standard',
    'TUSD': 'TrueUSD',
    'USDC': 'USD Coin',
    'USDT': 'Tether',
    'ETH': 'Ethereum'
}
