crypto_coins = {
    "stable_coins": ["BUSD","BGBP","PAX","TUSD","USDT", "USDC"],
    "popular_coins": ["BTC", "ETH", "BNB"]
}
crypto_tokens = {
    "Storage coins": ["AR","BLZ","BTTC","FIL", "HOT","PROM","RIF","SC","SNM","STORJ","STX"],
    "Meme": ["DOGE", "FLOKI", "PEPE","PEOPLE","SHIB"],
    "AI": ["-","AGIX","CTXC", "FET","MDT","NMR","OCEAN","PHB","WLD"],
    "Metaverse": ["ALICE","AXS","BURGER","COMBO","DAR","FLOKI","GHST","HIGH","ILV","MAGIC","MANA","MBOX","PYR","SAND","SLP","TLM","TVK"],
    "Infrastructure": ["ADX","ANT","API3","ARKM","ARPA","ASTR","ATA","BAT","BICO","CLV","CTK","CVC","DATA","DENT","LINK", "BAND"],
    "Fan Token": ["ACM","ALPINE","ASR","ATM","BAR","CHZ","CITY","JUV","LAZIO","OG","PORTO","PSG","SANTOS"],
    "Launchpad": ["ALPHA","ALPINE","ARKM","AXS","BAND","BETA","BNB","BTTC","C98","CELR","CTSI","DEGO","EDU","EGLD","FET","GFT","GMT","HOOK","ID","INJ","KAVA","LAZIO","LOKA","MATIC","ONE","PERL","PORTO","SAND","SFP","TKO","TROY","VOXEL","WRX"],
    "Launchpool": ["ALICE","ALPHA", "ASR","ATA","ATM","BEL","CITY","CTK","DAR","DODO","FLM","GAL","HARD","HFT","HIGH","JUV","KLAY","LIT","MAV","MBOX","MC","OG","PENDLE","PSG","QI","RDNT","SANTOS","SUI","TLM","UNFI","WING","XVS"],
    "POW": ["ANKR","BCH","BTC","CFX", "CKB","CTXC","DASH","DCR","DGB","DOGE","ETC","FLUX","IOTA","KDA","KMD","LTC","NKN","ONT","QKC","RIF","RVN","SC","TRB","WTC","XMR","XVG","ZEC","ZEN","ZIL"],
    "Layer 1/ Layer 2": ["ACA","ADA","ALGO","AMB","APT","ARB","ARDR","ARK","ARPA","ASTR","ATOM","AVAX","BNB","BTS","CELO","CELR","CFX","CHR","CKB","CTSI","CTXC","DCR","DOT","DREP","EGLD","ELF","EOS","ETC","ETH","FLOW","FLUX","FTM","GLMR","GNO","HBAR","HIVE","HOT","ICP","ICX","INJ","IOST","IOTA","IOTX","KAVA","KDA","KLAY","KSM","LOOM","LSK","LUNA","LUNC","MATIC","MINA","MOVR","NEAR","NULS","OMG","ONE","ONT","OP","OSMO","PHB","PROM","QKC","QTUM","REEF","REI","RIF","SCRT","SKL","SOL","STRAX","STX","SUI","SYS","TOMO","TRX","VET","VIDT","VITE","WAN","WAXP","XEM","XLM","XRP","XTZ","ZIL"],
    "NFT": ["AGLD","ALICE","APE","AUDIO","AXS","BNX","CHR","CHZ","COMBO","DAR","ENJ","ERN","FIO","GALA","GHST","GMT","HIGH","IMX","MAGIC","MANA","MBOX","OGN","PYR","RARE","SAND","SLP","SUPER","THETA","TVK","WAXP"],
    "Gaming": ["AGLD","ALICE","AXS","BNX","BURGER","COMBO","DAR","ENJ","FLOKI","GALA","GHST","ILV","IMX","LOKA","MAGIC","MANA","MBOX","MC","PLA","PYR","SAND","SLP","TLM","VOXEL","WAXP","YGG"],
    "Innovation": ["AGLD","ALICE","ALPHA","AMB","ARK","ARKM","ATA","ATM","AUCTION","BADGER","BAKE","BAR","BEL","BIFI","BNX","BSW","BTS","BURGER","CHESS","CREAM","CVP","CVX","DEGO","DEXE","DF","DODO","DREP","EPX","ERN","FIS","FLM","FLOKI","FOR","FRONT","FTT","GAL","GHST","GMX","GNS","HFT","HOOK","ID","JASMY","JUV","KP3R","LEVER","LINA","LIT","LQTY","MAGIC","MDX","MLN","OAX","OG","OM","OMG","OOKI","PENDLE","PEOPLE","PEPE","PERL","PERP","PHA","PNT","POLS","POND","PROM","PSG","RDNT","REEF","RPL","SLP","SNM","SRM","STG","SUN","SUPER","SUSHI","SYN","TORN","TRN","UFT","UNFI","VGX","VIDT","WING","WNXM","WRX","YFII"],
    "DeFi": ["1INCH","AAVE","ACA","AKRO","ALCX","ALPACA","AMP","ANKR","AST","AUCTION","AST","BADGER","BAKE","BAL","BAND","BEL","BETA","BIFI","BNT","BOND","BSW","BTS","C98","CAKE","CELO","CHESS","COMP","COTI","CREAM","CRV","CVP","CVX","DEGO","DEXE","DF","DIA","DODO","DYDX","EPX","FARM","FIDA","FIS","FLM","FOR","FORTH","FRONT","FXS","GHST","GMX","GNS","HARD","HFT","HIFI","IDEX","INJ","JOE","JST","KAVA","KLAY","KNC","KP3R","LDO","LEVER","LINA","LIT","LQTY","LRC","LUNA","LUNC","MAV","MBOX","MDX","MKR","MLN","MULTI","NMR","OM","OOKI","OSMO","PENDLE","PERP","PNT","POLS","POND","PROS","QI","QUICK","RAY","RDNT","REEF","REN","RIF","RPL","RSR","RUNE","SNX","SPELL","SRM","STG","SUN","SUPER","SUSHI","SYN","TRB","TRU","UFT","UMA","UNFI","UNI","USTC","WAXP","WING","WOO","XVS","YFI","YFII","ZRX"],
    "ETF": ["ADADOWN","ADADOWN","BNBDOWN","BNBUP","BTCDOWN","BTCUP","ETHDOWN","ETHUP"],
    "Polkadot": ["ACA","AKRO","ASTR","ATA","DOT","GLMR","KSM","LIT","PHA","REEF"],
}
crypto_dict = {
    '1INCH': '1inch',
    'AAVE': 'Aave',
    'ACA': 'Acala',
    'ACM': 'AC Milan Fan Token',
    'ADA': 'Cardano',
    'ADADOWN': 'ADA Down',
    'ADX': 'AdEx',
    'AGIX': 'SingularityNET',
    'AGLD': 'Adventure Gold',
    'AKRO': 'Akropolis',
    'ALCX': 'Alchemix',
    'ALGO': 'Algorand',
    'ALICE': 'MyNeighborAlice',
    'ALPACA': 'Alpaca Finance',
    'ALPHA': 'Alpha Finance Lab',
    'ALPINE': 'Alpine F1 Team Fan Token',
    'AMB': 'Ambrosus',
    'AMP': 'Amp',
    'ANKR': 'Ankr',
    'ANT': 'Aragon',
    'APE': 'ApeCoin',
    'API3': 'API3',
    'APT': 'Apt Coin',
    'AR': 'Arweave',
    'ARB': 'Arbitrum',
    'ARDR': 'Ardor',
    'ARK': 'Ark',
    'ARKM': 'ARKM',
    'ARPA': 'ARPA Chain',
    'ASR': 'AS Roma Fan Token',
    'AST': 'AirSwap',
    'ASTR': 'AstroTools',
    'ATA': 'Automata Network',
    'ATM': 'Atletico Madrid Fan Token',
    'ATOM': 'Cosmos',
    'AUCTION': 'Auction',
    'AUDIO': 'Audius',
    'AVAX': 'Avalanche',
    'AXS': 'Axie Infinity',
    'BADGER': 'Badger DAO',
    'BAKE': 'BakeryToken',
    'BAL': 'Balancer',
    'BAND': 'Band Protocol',
    'BAR': 'Barcelona FC Fan Token',
    'BAT': 'Basic Attention Token',
    'BCH': 'Bitcoin Cash',
    'BEL': 'Bella Protocol',
    'BETA': 'Beta Finance',
    'BICO': 'Biconomy',
    'BIFI': 'Beefy.Finance',
    'BLZ': 'Bluzelle',
    'BNB': 'Binance Coin',
    'BNBDOWN': 'BNB Down',
    'BNBUP': 'BNB Up',
    'BNT': 'Bancor',
    'BNX': 'Balancer NXY',
    'BOND': 'BarnBridge',
    'BSW': 'Binance Smart Chain',
    'BTC': 'Bitcoin',
    'BTCDOWN': 'BTC Down',
    'BTCUP': 'BTC Up',
    'BTS': 'BitShares',
    'BTTC': 'Bitcoin Token',
    'BURGER': 'Burger Swap',
    'C98': 'Coin98',
    'CAKE': 'PancakeSwap',
    'CELO': 'Celo',
    'CELR': 'Celer Network',
    'CFX': 'Conflux Network',
    'CHESS': 'ChessCoin',
    'CHR': 'Chromia',
    'CHZ': 'Chiliz',
    'CITY': 'Manchester City Fan Token',
    'CKB': 'Nervos Network',
    'CLV': 'Clover Finance',
    'COMBO': 'Rocket Vault-Rocket Token',
    'COMP': 'Compound',
    'COTI': 'COTI',
    'CREAM': 'Cream Finance',
    'CRV': 'Curve DAO Token',
    'CTK': 'CertiK',
    'CTSI': 'Cartesi',
    'CTXC': 'Cortex',
    'CVC': 'Civic',
    'CVP': 'PowerPool',
    'CVX': 'Convex Finance',
    'DAR': 'Darwinia Network',
    'DASH': 'Dash',
    'DATA': 'Streamr DATAcoin',
    'DCR': 'Decred',
    'DEGO': 'DEGO Finance',
    'DENT': 'Dent',
    'DEXE': 'DeXe',
    'DF': 'Dfinance',
    'DGB': 'DigiByte',
    'DIA': 'DIA',
    'DODO': 'DODO',
    'DOGE': 'Dogecoin',
    'DOT': 'Polkadot',
    'DREP': 'Drep [new]',
    'DYDX': 'dYdX',
    'EDU': 'EduCoin',
    'EGLD': 'Elrond',
    'ELF': 'aelf',
    'ENJ': 'Enjin Coin',
    'EOS': 'EOS',
    'EPX': 'EpiK Protocol',
    'ERN': 'Ethernity Chain',
    'ETC': 'Ethereum Classic',
    'ETH': 'Ethereum',
    'ETHDOWN': 'ETH Down',
    'ETHUP': 'ETH Up',
    'FARM': 'Harvest Finance',
    'FET': 'Fetch.ai',
    'FIDA': 'Bonfida',
    'FIL': 'Filecoin',
    'FIO': 'FIO Protocol',
    'FIS': 'StaFi',
    'FLM': 'Flamingo Finance',
    'FLOKI': 'Floki Inu',
    'FLOW': 'Flow',
    'FLUX': 'Flux',
    'FOR': 'ForTube',
    'FORTH': 'Ampleforth Governance Token',
    'FRONT': 'Frontier',
    'FTM': 'Fantom',
    'FTT': 'FTX Token',
    'FXS': 'Frax Share',
    'GAL': 'Galatasaray Fan Token',
    'GALA': 'Gala',
    'GFT': 'Gifted Hands Token',
    'GHST': 'Aavegotchi',
    'GLMR': 'Golom',
    'GMT': 'GoMining Token',
    'GMX': 'GMX',
    'GNO': 'Gnosis',
    'GNS': 'Genesis Shards',
    'HARD': 'HARD Protocol',
    'HBAR': 'Hedera Hashgraph',
    'HFT': 'HollaEx Token',
    'HIFI': 'Hifi Finance',
    'HIGH': 'Highstreet',
    'HIVE': 'Hive',
    'HOOK': 'HOOK',
    'HOT': 'Holo',
    'ICP': 'Internet Computer',
    'ICX': 'ICON',
    'ID': 'Everest',
    'IDEX': 'IDEX',
    'ILV': 'Illuvium',
    'IMX': 'Immutable X',
    'INJ': 'Injective Protocol',
    'IOST': 'IOST',
    'IOTA': 'IOTA',
    'IOTX': 'IoTeX',
    'JASMY': 'JasmyCoin',
    'JOE': 'JOE',
    'JST': 'JUST',
    'JUV': 'Juventus Fan Token',
    'KAVA': 'Kava',
    'KDA': 'Kadena',
    'KLAY': 'Klaytn',
    'KMD': 'Komodo',
    'KNC': 'Kyber Network',
    'KP3R': 'Keep3rV1',
    'KSM': 'Kusama',
    'LAZIO': 'Lazio Fan Token',
    'LDO': 'Lido DAO Token',
    'LEVER': 'Leverj',
    'LINA': 'Linear',
    'LINK': 'Chainlink',
    'LIT': 'Litentry',
    'LOKA': 'Lokanet',
    'LOOM': 'Loom Network',
    'LQTY': 'Liquity',
    'LRC': 'Loopring',
    'LSK': 'Lisk',
    'LTC': 'Litecoin',
    'LUNA': 'Terra',
    'LUNC': 'LunarCRUSH',
    'MAGIC': 'aXpire',
    'MANA': 'Decentraland',
    'MATIC': 'Polygon',
    'MAV': 'Mavro',
    'MBOX': 'Mobox',
    'MC': 'Mercury',
    'MDT': 'Measurable Data Token',
    'MDX': 'Mdex',
    'MINA': 'Mina Protocol',
    'MKR': 'Maker',
    'MLN': 'Enzyme',
    'MOVR': 'Moonriver',
    'MULTI': 'MultiVAC',
    'NEAR': 'NEAR Protocol',
    'NKN': 'NKN',
    'NMR': 'Numeraire',
    'NULS': 'NULS',
    'OAX': 'OAX',
    'OCEAN': 'Ocean Protocol',
    'OG': 'OG Fan Token',
    'OGN': 'Origin Protocol',
    'OM': 'MANTRA DAO',
    'OMG': 'OMG Network',
    'ONE': 'Harmony',
    'ONT': 'Ontology',
    'OOKI': 'Ooki Protocol',
    'OP': 'OPium',
    'OSMO': 'OSMO',
    'PENDLE': 'Pendle',
    'PEOPLE': 'People',
    'PEPE': 'PepeCash',
    'PERL': 'Perlin',
    'PERP': 'Perpetual Protocol',
    'PHA': 'Phala Network',
    'PHB': 'Phoenix',
    'PLA': 'PlayDapp',
    'PNT': 'pNetwork',
    'POLS': 'Polkastarter',
    'POND': 'Marlin',
    'PORTO': 'Porto',
    'PROM': 'Prometeus',
    'PROS': 'Prosper',
    'PSG': 'Paris Saint-Germain Fan Token',
    'PYR': 'Pyrrha',
    'QI': 'Qi Swap',
    'QKC': 'QuarkChain',
    'QTUM': 'Qtum',
    'QUICK': 'QuickSwap',
    'RARE': 'SuperRare',
    'RAY': 'Raydium',
    'RDNT': 'Radiant',
    'REEF': 'Reef Finance',
    'REI': 'Rubius',
    'REN': 'Ren',
    'RIF': 'RIF Token',
    'RPL': 'Rocket Pool',
    'RSR': 'Reserve Rights',
    'RUNE': 'THORChain',
    'RVN': 'Ravencoin',
    'SAND': 'The Sandbox',
    'SANTOS': 'Santos FC Fan Token',
    'SC': 'Siacoin',
    'SCRT': 'Secret',
    'SFP': 'SafePal',
    'SHIB': 'Shiba Inu',
    'SKL': 'Skale Network',
    'SLP': 'Smooth Love Potion',
    'SNM': 'SONM',
    'SNX': 'Synthetix',
    'SOL': 'Solana',
    'SPELL': 'Spell Token',
    'SRM': 'Serum',
    'STG': 'Stargazer',
    'STORJ': 'Storj',
    'STRAX': 'Stratis',
    'STX': 'Stacks',
    'SUI': 'Suterusu',
    'SUN': 'Sun Token',
    'SUPER': 'SuperFarm',
    'SUSHI': 'SushiSwap',
    'SYN': 'SynLev',
    'SYS': 'Syscoin',
    'THETA': 'Theta Network',
    'TKO': 'Tokocrypto',
    'TLM': 'Alien Worlds',
    'TOMO': 'TomoChain',
    'TORN': 'Tornado Cash',
    'TRB': 'Tellor',
    'TRN': 'Trodl',
    'TROY': 'Troy',
    'TRU': 'TrueFi',
    'TRX': 'TRON',
    'TVK': 'Terra Virtua Kolect',
    'UFT': 'UniLend Finance',
    'UMA': 'UMA',
    'UNFI': 'Unifi Protocol DAO',
    'UNI': 'Uniswap',
    'USTC': 'USDC Token',
    'VET': 'VeChain',
    'VGX': 'Voyager Token',
    'VIDT': 'VIDT Datalink',
    'VITE': 'VITE',
    'VOXEL': 'Voxel',
    'WAN': 'Wanchain',
    'WAXP': 'WAX',
    'WING': 'Wing Finance',
    'WLD': 'World Token',
    'WNXM': 'Wrapped NXM',
    'WOO': 'WOO Network',
    'WRX': 'WazirX',
    'WTC': 'Waltonchain',
    'XEM': 'NEM',
    'XLM': 'Stellar',
    'XMR': 'Monero',
    'XRP': 'XRP',
    'XTZ': 'Tezos',
    'XVG': 'Verge',
    'XVS': 'Venus',
    'YFI': 'yearn.finance',
    'YFII': 'Dfi.Money',
    'YGG': 'Yield Guild Games',
    'ZEC': 'Zcash',
    'ZEN': 'Horizen',
    'ZIL': 'Zilliqa',
    'ZRX': '0x'
}
fiat_dict = {
    'BGBP': 'Binance GBP',
    'BUSD': 'Binance USD',
    'BTC': 'Bitcoin',
    'BNB': 'Binance Coin',
    'PAX': 'Paxos Standard',
    'TUSD': 'TrueUSD',
    'USDC': 'USD Coin',
    'USDT': 'Tether',
    'ETH': 'Ethereum'
}


